name: 功能请求
description: 提出新功能或改进建议
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: 功能描述
      description: 清晰描述你想要的功能
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: 动机
      description: 为什么需要这个功能，解决什么问题
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: 建议方案
      description: 如果有想法，描述你期望的实现方式
    validations:
      required: false